EXPERIMENT:
  NAME: ""
  TAG: "kd,deit,res18"
  PROJECT: "tinyimagenet200_baselines"
DATASET:
  TYPE: "tinyimagenet200"
DISTILLER:
  TYPE: "KD"
  TEACHER: "deit"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"