EXPERIMENT:
  NAME: ""
  TAG: "MLD,res32x4,res8x4"
  PROJECT: "tinyimagenet200_baselines"
DATASET:
  TYPE: "tinyimagenet200"
DISTILLER:
  TYPE: "MLD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "MLD"










































